# Description: Documentation de l'API pour OPIB.
# copier coller sur https://editor.swagger.io/ pour visualiser la documentation

openapi: 3.0.0
info:
  title: API Documentation
  description: Documentation de l'API pour OPIB.
  version: 1.0.1
servers:
  - url: http://localhost:8000/api
    description: Serveur local

paths:
  /users:
    get:
      summary: Récupérer tous les utilisateurs
      responses:
        '200':
          description: Liste des utilisateurs

    post:
      summary: Créer un nouvel utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Username:
                  type: string
                hash_passwd_b64:
                  type: string
      responses:
        '201':
          description: Utilisateur créé

  /users/{id_user}:
    get:
      summary: Récupérer un utilisateur par ID
      parameters:
        - name: id_user
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Détails de l'utilisateur

    put:
      summary: Mettre à jour un utilisateur
      parameters:
        - name: id_user
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Username:
                  type: string
                hash_passwd_b64:
                  type: string
      responses:
        '200':
          description: Utilisateur mis à jour

    delete:
      summary: Supprimer un utilisateur
      parameters:
        - name: id_user
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Utilisateur supprimé

  /historique/{id_user}:
    get:
      summary: Récupérer l'historique des connexions d'un utilisateur
      parameters:
        - name: id_user
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Liste des connexions de l'utilisateur

  /rapport/{id_user}:
    get:
      summary: Récupérer tous les rapports de l'utilisateur
      parameters:
        - name: id_user
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Liste des rapports de l'utilisateur
  

  /rapport/{id_user}/{id_analyse}:

    get:
      summary: Récupérer un rapport par ID
      parameters:
        - name: id_user
          in: path
          required: true
          schema:
            type: string
        - name: id_analyse
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Détails du rapport
      
    post:
      summary: Créer un nouveau rapport
      parameters:
        - name: id_user
          in: path
          required: true
          schema:
            type: string
        - name: id_analyse
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_user:
                  type: string
                id_analyse:
                  type: integer
                name:
                  type: string
                encrypted_file_aes:
                  type: string
      responses:
        '201':
          description: Rapport créé

    put: 
      summary: Mettre à jour un rapport
      parameters:
        - name: id_user
          in: path
          required: true
          schema:
            type: string
        - name: id_analyse
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_user:
                  type: string
                id_analyse:
                  type: integer
                name:
                  type: string
                encrypted_file_aes:
                  type: string
      responses:
        '200':
          description: Rapport mis à jour

    delete:
      summary: Supprimer un rapport
      parameters:
        - name: id_user
          in: path
          required: true
          schema:
            type: string
        - name: id_analyse
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Rapport supprimé
  
  /results/{id_analyse}:
    get:
      summary: Récupérer tous les résultats
      parameters:
        - name: id_analyse
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Liste des résultats

    post:
      summary: Créer un nouveau résultat
      parameters:
        - name: id_analyse
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_analyse:
                  type: integer
                s1:
                  type: string
                s2:
                  type: string
                s3:
                  type: string
                s4:
                  type: string
      responses:
        '201':
          description: Résultat créé
      
    put:
      summary: Mettre à jour un résultat
      parameters:
        - name: id_analyse
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_analyse:
                  type: integer
                s1:
                  type: string
                s2:
                  type: string
                s3:
                  type: string
                s4:
                  type: string
      responses:
        '200':
          description: Résultat mis à jour

  /pending_analyse/{id_analyse}:
    get:
      summary: Récupérer les analyses en attente
      parameters:
        - name: id_analyse
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Liste des analyses en attente

    post:
      summary: Créer une nouvelle analyse en attente
      parameters:
        - name: id_analyse
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_analyse:
                  type: integer
                id_user:
                  type: string
                s1:
                  type: boolean
                s2:
                  type: boolean
                s3:
                  type: boolean
                s4:
                  type: boolean
      responses:
        '201':
          description: Analyse en attente créée

    delete:
      summary: Supprimer une analyse en attente
      parameters:
        - name: id_analyse
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Analyse en attente supprimée
