apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    -- TODO : modifier les valeurs des varchars (default 50) 

    #------------------------------------------------------------
    # Table: User
    #------------------------------------------------------------

    CREATE TABLE User(
                         user_email      VARCHAR(325) NOT NULL,
                         hash_passwd_b64 VARCHAR(50) NOT NULL,
                         CONSTRAINT User_PK PRIMARY KEY (user_email)
    ) ENGINE=InnoDB;

    #------------------------------------------------------------
    # Table: historique_connexion
    #-----------------------------------------------------------

    CREATE TABLE historique_connexion(
                                         id_connexion INT AUTO_INCREMENT NOT NULL,
                                         user_email   VARCHAR(325) NOT NULL,
                                         timestamp    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                         location     VARCHAR(50) NOT NULL,
                                         plateforme   VARCHAR(50) NOT NULL,
                                         CONSTRAINT historique_connexion_PK PRIMARY KEY (id_connexion),
                                         CONSTRAINT historique_connexion_User_FK FOREIGN KEY (user_email) REFERENCES User(user_email) ON DELETE CASCADE
    ) ENGINE=InnoDB;

    #------------------------------------------------------------
    # Table: rapport
    #------------------------------------------------------------

    CREATE TABLE rapport(
                            id_analyse         INT NOT NULL AUTO_INCREMENT,
                            user_email         VARCHAR(325) NOT NULL,
                            name               VARCHAR(50),
                            encrypted_file_aes VARCHAR(50),
                            isreaded           BOOL NOT NULL DEFAULT FALSE,
                            date_declanchement TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            CONSTRAINT rapport_PK PRIMARY KEY (id_analyse),
                            CONSTRAINT rapport_User_FK FOREIGN KEY (user_email) REFERENCES User(user_email) ON DELETE CASCADE
    ) ENGINE=InnoDB;

    #------------------------------------------------------------
    # Table: pending_analyse
    #------------------------------------------------------------

    CREATE TABLE pending_analyse(
                                    id_analyse INT NOT NULL,
                                    user_email VARCHAR(325) NOT NULL,
                                    s1         BOOL NOT NULL,
                                    s2         BOOL NOT NULL,
                                    s3         BOOL NOT NULL,
                                    s4         BOOL NOT NULL,
                                    CONSTRAINT pending_analyse_rapport_FK FOREIGN KEY (id_analyse) REFERENCES rapport(id_analyse) ON DELETE CASCADE,
                                    CONSTRAINT pending_analyse_PK PRIMARY KEY (id_analyse),
                                    CONSTRAINT pending_analyse_User_FK FOREIGN KEY (user_email) REFERENCES User(user_email) ON DELETE CASCADE
    ) ENGINE=InnoDB;

    #------------------------------------------------------------
    # Table: results
    #------------------------------------------------------------

    CREATE TABLE results(
                            id_analyse INT NOT NULL,
                            s1         VARCHAR(50) NOT NULL,
                            s2         VARCHAR(50) NOT NULL,
                            s3         VARCHAR(50) NOT NULL,
                            s4         VARCHAR(50) NOT NULL,
                            CONSTRAINT results_rapport_FK FOREIGN KEY (id_analyse) REFERENCES rapport(id_analyse) ON DELETE CASCADE,
                            CONSTRAINT results_PK PRIMARY KEY (id_analyse)
    ) ENGINE=InnoDB;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpass
            - name: MYSQL_DATABASE
              value: mqtt_db
            - name: MYSQL_USER
              value: mqttuser
            - name: MYSQL_PASSWORD
              value: mqttpass
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30036
  selector:
    app: mysql